# Generated by Django 4.1.6 on 2023-02-05 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['id'], 'verbose_name': 'EventType', 'verbose_name_plural': 'EventType'},
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
