# Generated by Django 4.1.6 on 2023-02-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_eventtype_options_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['id']},
        ),
    ]
